### PR TITLE
Better Search

### PR DESCRIPTION
**Pull request by Injng**
Currently, the search system is kind of bad. Here's why:

    Depends on an unnecessary third-party library (pagefind)
    Search results only load after a carriage return is passed
    The search results are bad, e.g. if you search "lin" only "linandrew" is shown, but not "jianglin"
    The search results unnecessarily return the home page
    The search results don't allow immediate zero-click access to statistics
    The style is unreadable: everything is dark

This pull request attempts to fix the above issues. In particular, we:

    Remove the dependency on pagefind by implementing custom JS
    Search results update dynamically as input changes in the search bar
    The search results are not bad
    The search updates the actual rankings table, which means you can immediately see statistics
    The style is actually readable

Note that the striped patterning for the table is somewhat broken after updating,
this may warrant additional discussion/changes.

### CODE REVIEW

**Comment by Injng** [comment]
New push with the templates file actually changed

**Comment by Injng** [comment]
Verified to be working with `a.sh`.

**Comment by Injng** [comment]
Merged by https://github.com/lelandstocks/lelandstocks.github.io/commit/f4d9c3a1493730230d227469f222ca79e6d1f742

**Comment by pythoncrazy** [comment]
yep

**Pull request closed without merging**
